# Generated by Django 5.2.7 on 2025-11-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about', 'About'), ('service', 'Service'), ('skill', 'Skill'), ('project', '実績'), ('contact', 'Contact')], max_length=20, unique=True, verbose_name='セクションタイプ')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='サブタイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': 'ポートフォリオセクション',
                'verbose_name_plural': 'ポートフォリオセクション',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(verbose_name='説明')),
                ('technologies', models.CharField(help_text='カンマ区切りで入力', max_length=500, verbose_name='使用技術')),
                ('project_url', models.URLField(blank=True, verbose_name='プロジェクトURL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '実績プロジェクト',
                'verbose_name_plural': '実績プロジェクト',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
