# Generated by Django 5.2.7 on 2025-11-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Miyakawa Code', max_length=200, verbose_name='サイト名')),
                ('site_description', models.CharField(blank=True, max_length=500, verbose_name='サイト説明')),
                ('site_keywords', models.CharField(blank=True, help_text='カンマ区切りで入力', max_length=500, verbose_name='SEOキーワード')),
                ('footer_text', models.CharField(blank=True, max_length=200, verbose_name='フッターテキスト')),
            ],
            options={
                'verbose_name': 'サイト設定',
                'verbose_name_plural': 'サイト設定',
            },
        ),
    ]
