# Generated by Django 5.2.7 on 2025-11-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=100, verbose_name='セクションタイトル')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='サブタイトル')),
                ('profile_image', models.ImageField(blank=True, upload_to='about/', verbose_name='プロフィール画像')),
                ('introduction', models.TextField(verbose_name='自己紹介文')),
                ('career_summary', models.TextField(verbose_name='経歴要約')),
                ('philosophy', models.TextField(blank=True, verbose_name='仕事への想い・哲学')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': 'Aboutセクション',
                'verbose_name_plural': 'Aboutセクション',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='指標名')),
                ('value', models.CharField(help_text='例: 100%, 50+, 100日, 14年', max_length=20, verbose_name='数値')),
                ('description', models.CharField(max_length=100, verbose_name='説明')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='アイコンクラス')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': '実績指標',
                'verbose_name_plural': '実績指標',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='まずはお気軽にご相談ください', max_length=100, verbose_name='セクションタイトル')),
                ('description', models.TextField(default='ビジネス課題の解決から技術的な実装まで、どんなご相談でもお気軽にお声がけください。', verbose_name='説明文')),
                ('email_address', models.EmailField(default='contact@miyakawa.code', max_length=254, verbose_name='メールアドレス')),
                ('email_button_text', models.CharField(default='メールでお問い合わせ', max_length=50, verbose_name='メールボタンテキスト')),
                ('slack_url', models.URLField(default='https://slack.com/intl/ja-jp/', verbose_name='Slack URL')),
                ('slack_button_text', models.CharField(default='Slackでご相談', max_length=50, verbose_name='Slackボタンテキスト')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': 'お問い合わせセクション',
                'verbose_name_plural': 'お問い合わせセクション',
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='🐍 Python 100日チャレンジ運行中！', max_length=100, verbose_name='バッジテキスト')),
                ('main_title', models.CharField(default='毎日の学習で技術力を向上', max_length=100, verbose_name='メインタイトル')),
                ('description', models.TextField(default='継続的な学習を通じて、最新のPython技術やAI/機械学習分野のスキルを日々更新しています。', verbose_name='説明文')),
                ('button_text', models.CharField(default='進捗を確認する', max_length=50, verbose_name='ボタンテキスト')),
                ('button_link', models.CharField(default='/blog/', max_length=100, verbose_name='ボタンリンク')),
                ('background_color', models.CharField(default='bg-gray-900', max_length=50, verbose_name='背景色（Tailwind）')),
                ('text_color', models.CharField(default='text-white', max_length=50, verbose_name='文字色（Tailwind）')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': 'CTAセクション',
                'verbose_name_plural': 'CTAセクション',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='特徴タイトル')),
                ('description', models.TextField(verbose_name='説明')),
                ('icon_class', models.CharField(blank=True, help_text='SVGアイコンのクラス名（任意）', max_length=100, verbose_name='アイコンクラス')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': '特徴',
                'verbose_name_plural': '特徴（他のエンジニアとの違い）',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title_line1', models.CharField(default='ビジネス課題から実', max_length=100, verbose_name='メインタイトル1行目')),
                ('main_title_line2', models.CharField(default='装まで', max_length=100, verbose_name='メインタイトル2行目')),
                ('main_title_line3', models.CharField(default='一人で解決する', max_length=100, verbose_name='メインタイトル3行目')),
                ('main_title_line4', models.CharField(default='エンジニア', max_length=100, verbose_name='メインタイトル4行目')),
                ('subtitle_tech', models.CharField(default='Python 3.13 • Flask 3.1.2', max_length=100, verbose_name='技術情報')),
                ('author_name', models.CharField(default='宮川 剛', max_length=50, verbose_name='氏名')),
                ('author_description', models.CharField(default='14年の経験。プログラミング歴から起業ビジネスまで幅広い解決力', max_length=200, verbose_name='自己紹介')),
                ('cta_primary_text', models.CharField(default='サービス詳細', max_length=50, verbose_name='プライマリボタンテキスト')),
                ('cta_primary_link', models.CharField(default='#services', max_length=100, verbose_name='プライマリボタンリンク')),
                ('cta_secondary_text', models.CharField(default='お問い合わせ', max_length=50, verbose_name='セカンダリボタンテキスト')),
                ('cta_secondary_link', models.CharField(default='#contact', max_length=100, verbose_name='セカンダリボタンリンク')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': 'ヒーローセクション',
                'verbose_name_plural': 'ヒーローセクション',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スキル名')),
                ('experience_years', models.IntegerField(verbose_name='経験年数')),
                ('proficiency_percentage', models.IntegerField(help_text='0-100の数値で入力', verbose_name='習熟度（%）')),
                ('description', models.TextField(blank=True, verbose_name='詳細説明')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
            ],
            options={
                'verbose_name': 'スキル',
                'verbose_name_plural': 'スキル',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='portfoliosection',
            options={'ordering': ['order'], 'verbose_name': 'ポートフォリオセクション（旧）', 'verbose_name_plural': 'ポートフォリオセクション（旧）'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-project_date', '-created_at'], 'verbose_name': '提供サービス・プロジェクト', 'verbose_name_plural': '提供サービス・プロジェクト'},
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, verbose_name='デモURL'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='注目プロジェクト'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name='プロジェクト実施日'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='projects/', verbose_name='サムネイル画像'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='カンマ区切りで入力', max_length=500, verbose_name='使用技術・特徴'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='サービス・プロジェクト名'),
        ),
    ]
