# Generated by Django 5.2.7 on 2025-11-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_aboutsection_achievement_contactsection_ctasection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='main_title_line1',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='main_title_line2',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='main_title_line3',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='main_title_line4',
        ),
        migrations.AddField(
            model_name='herosection',
            name='main_title',
            field=models.TextField(default='ビジネス課題から実\n装まで\n一人で解決する\nエンジニア', help_text='改行位置で分割されます', verbose_name='メインタイトル'),
        ),
    ]
