# Generated by Django 5.2.7 on 2025-11-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_herosection_main_title_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='推奨サイズ: 600px × 384px（アスペクト比 25:16）', null=True, upload_to='hero/', verbose_name='ヒーロー画像'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_alt',
            field=models.CharField(blank=True, help_text='アクセシビリティのため、画像の説明を入力してください', max_length=200, verbose_name='画像のalt属性'),
        ),
    ]
