# Generated by Django 5.2.7 on 2025-11-06 04:33

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_herosection_hero_image_herosection_hero_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='hero_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='アップロード時に自動的に600px × 384px（アスペクト比 25:16）にリサイズされます', null=True, upload_to='hero/', verbose_name='ヒーロー画像'),
        ),
    ]
