# Generated by Django 5.2.7 on 2025-11-06 05:02

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_herosection_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='アップロード時に自動的に400px × 240px（アスペクト比 5:3）にリサイズされます', null=True, upload_to='projects/', verbose_name='サムネイル画像'),
        ),
    ]
